name: Check

on:
  push:
    branches:
      - main
      - 'renovate/**'
    paths:
      - '*.json5?'

      - '.github/workflows/check.ya?ml'

  pull_request:
    branches:
      - main
    paths:
      - '*.json5?'

      - '.github/workflows/check.ya?ml'

  workflow_call:
  workflow_dispatch:

  schedule:
    # Also run the check every month.
    - cron: '0 0 1 * *'

jobs:
  code-quality:
    name: Code Quality

    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash --noprofile --norc -euxo pipefail {0}

    steps:
      - name: Check out repository
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          persist-credentials: false

      - name: Download and run renovate-config-validator
        run: |
          # Support advanced globbing patterns.
          shopt -s dotglob globstar nullglob

          # Download and run renovate-config-validator
          npx --yes --package renovate@latest -- renovate-config-validator --strict \
            ./*.json \
            ./*.json5
