name: Check

on:
  push:
    branches:
      - main
      - 'renovate/**'
    paths:
      - '*.json5?'

  pull_request:
    branches:
      - main
    paths:
      - '*.json5?'

  workflow_call:
  workflow_dispatch:

  schedule:
    # Also run the check every month.
    - cron: '0 0 1 * *'

jobs:
  code-quality:
    name: Code Quality

    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash --noprofile --norc -euxo pipefail {0}

    steps:
      - name: Check out repository
        uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1
        with:
          persist-credentials: false

      - name: Download and run renovate-config-validator
        run: |
          # Support advanced globbing patterns.
          shopt -s dotglob globstar nullglob

          # Download and run renovate-config-validator
          npx --yes --package renovate -- renovate-config-validator --strict -- \
            *.json \
            *.json5
